# Project: BooleanExpressionCalculator
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 
LINKOBJ  = 
LIBS     = -L"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/lib" -L"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/include" -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/include" -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Izaan/Work/University/university docs/Semester 1/computer/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = BooleanExpressionCalculator.exe
CXXFLAGS = $(CXXINCS) -pg
CFLAGS   = $(INCS) -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)
